# Kanari L2 Validator Node Docker Compose
version: '3.8'

services:
  # Kanari Validator Node
  kanari-validator:
    build:
      context: .
      dockerfile: docker/Dockerfile.validator
    container_name: kanari-validator
    restart: unless-stopped
    ports:
      - "6767:6767"    # RPC port
      - "9184:9184"    # Metrics port
      - "30333:30333"  # P2P port
    volumes:
      - kanari-data:/data
      - kanari-logs:/logs
      - ./config/validator.yaml:/etc/kanari/validator.yaml:ro
      - ./keys:/keys:ro
    environment:
      - RUST_LOG=info
      - KANARI_DATA_DIR=/data
      - KANARI_CONFIG_FILE=/etc/kanari/validator.yaml
    networks:
      - kanari-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
  # Bitcoin Node (for Bitcoin integration)
  bitcoin-node:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin-node
    restart: unless-stopped
    ports:
      - "18443:18443"  # RPC port
      - "18444:18444"  # P2P port
    volumes:
      - bitcoin-data:/root/.bitcoin
      - ./config/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
    command: >
      bitcoind
      -server=1
      -regtest=1
      -rpcuser=kanariuser
      -rpcpassword=kanaripass
      -rpcport=18443
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -txindex=1
      -daemon=0
    networks:
      - kanari-net
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=kanariuser", "-rpcpassword=kanaripass", "getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Prometheus (for monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: kanari-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - kanari-net

  # Grafana (for visualization)
  grafana:
    image: grafana/grafana:latest
    container_name: kanari-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - kanari-net

  # Nginx (reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: kanari-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - kanari-validator
    networks:
      - kanari-net

  # Log aggregator
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: kanari-logs
    restart: unless-stopped
    volumes:
      - kanari-logs:/logs:ro
      - ./config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    depends_on:
      - kanari-validator
    networks:
      - kanari-net

networks:
  kanari-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  kanari-data:
    driver: local
  kanari-logs:
    driver: local
  bitcoin-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
