[build]
rustflags = ["--cfg", "tokio_unstable", "-C", "force-frame-pointers=yes", "-C", "force-unwind-tables=yes"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=lld", "-C", "force-frame-pointers=yes", "-C", "force-unwind-tables=yes", "-C", "target-cpu=skylake"]

# 64 bit MSVC
[target.x86_64-pc-windows-msvc]
rustflags = [
    "--cfg",
    "tokio_unstable",
    "-C",
    "force-frame-pointers=yes",
    "-C",
    "force-unwind-tables=yes",
    "-C",
    "link-arg=/STACK:8000000", # Set stack to 8 MB
    # Remove static linking for better compatibility with libgit2
    # "-Ctarget-feature=+crt-static",
    # Use dynamic linking instead
    "-C", "link-arg=advapi32.lib",
    "-C", "link-arg=secur32.lib", 
    "-C", "link-arg=userenv.lib",
    "-C", "link-arg=crypt32.lib",
    "-C", "link-arg=ws2_32.lib",
    "-C", "link-arg=bcrypt.lib"
]

[alias]
a = "add"
au = "audit"
b = "build"
br = "build --release"
c = "check"
cl = "clean"
d = "doc --open"
r = "run"
rr = "run --release"
up = "update"


wasm = "build --target wasm32-unknown-unknown --release"
wasm-debug = "build --target wasm32-unknown-unknown"
