# Prometheus Configuration for Kanari L2 Validator Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "kanari_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Kanari Validator Metrics
  - job_name: 'kanari-validator'
    static_configs:
      - targets: ['kanari-validator:9184']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # Bitcoin Node Metrics (if available)
  - job_name: 'bitcoin-node'
    static_configs:
      - targets: ['bitcoin-node:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
